const aliasMap: Record<string, string> = {
  "city": "Manchester City",
  "man-city": "Manchester City",
  "al-ahly": "Al Ahly",
  "ahly": "Al Ahly",
  "fluminense": "Fluminense",
  "flu": "Fluminense",
  "auckland": "Auckland City",
  "auckland-city": "Auckland City",
  "club-america": "Club América",
  "america": "Club América",
  "madrid": "Real Madrid",
  "realmadrid": "Real Madrid",
  "boca": "Boca Juniors",
  "boca-juniors": "Boca Juniors",
  "sundowns": "Mamelodi Sundowns",
  "sundown": "Mamelodi Sundowns",
  "ural": "Urawa Red Diamonds",
  "urawa": "Urawa Red Diamonds",
  "leon": "Club León",
  "feyenoord": "Feyenoord",
  "atletico": "Atlético Mineiro",
  "atletico-mg": "Atlético Mineiro",
  "inter-miami": "Inter Miami",
  "miami": "Inter Miami",
  "al-hilal": "Al Hilal",
  "hilal": "Al Hilal",
  "palmeiras": "Palmeiras",
  "zamalek": "Zamalek"
};

export default aliasMap;
